# Generated by Django 3.1.7 on 2021-03-20 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animeName', models.CharField(max_length=50)),
                ('produtora', models.CharField(max_length=50)),
                ('lancamento', models.IntegerField()),
                ('sinopse', models.CharField(max_length=200)),
            ],
        ),
    ]
